### ISSUE TITLE
Compatibility with AngularJS 1.4.x

### ISSUE THREAD

**Issue by Puigcerber** [Puigcerber/angular-country-picker#1]
Because of the changes introduced in [7fda214c](https://github.com/angular/angular.js/commit/7fda214c4f65a6a06b25cf5d5aff013a364e9cef) where a major refactoring of `select` and `ngOptions` have been accomplished, this directive is not compatible with the current AngularJS 1.4 beta versions.

**Comment by y4nnick** [comment]
Are you planning to fix this?

**Comment by Puigcerber** [comment]
Hi @y4nnick! 

I tried to solve it but I couldn't find a clean way to do it. So now that 1.4 is stable I should try to find some time to check it again.

Cheers, Pablo.
