### ISSUE TITLE
Make countries list publicly available

### ISSUE THREAD

**Issue by leitasat** [Puigcerber/angular-country-picker#4]
Hello!

I would like to suggest the following enhancement: https://github.com/Puigcerber/angular-country-picker/pull/3 
It makes the countries list available throughout application which might be useful to decode labels.

**Comment by Puigcerber** [comment]
Hi @leitasat! Welcome and thanks for contributing, but what do you mean with "decode labels"?

For the next time, there is no need to open an issue after you have created a pull request, it should be the other way around. You could have made the title of #3 as descriptive as this one and add the description so we could discuss it there. ;)

Cheers, Pablo.
