### ISSUE TITLE
Set countries list after app run

### ISSUE THREAD

**Issue by chOse** [Puigcerber/angular-country-picker#9]
I get the device language on app run.
I'd like to change the countries list according to device language.
How should I proceed to change the countries list after app run ?

Thank you!

**Comment by Puigcerber** [comment]
Hi @chOse!

The `run` phase happens after the `config` and therefore is not possible. If you want to translate country names to a different language I would go with using [angular-translate](https://github.com/angular-translate/angular-translate).

Cheers, Pablo.

**Comment by chOse** [comment]
Thanks for your reply.
Unfortunately, this solution doesn't sounds so easy to implement for me as I already use angular-gettext for translating my app.
I'd like not to have the full countries list in my expressions dictionnary, since I can download translated ISO countries lists...
Plus I think that it'd be interesting if we could edit the countries list on the fly as it is possible on some similar module.

**Comment by Puigcerber** [comment]
What do you show depending of device the language? Different countries or translated country names?

What do you mean by editing the country list on the fly?

**Comment by chOse** [comment]
I show translated country names.
Editing the country list on the fly would mean being able, in a controller for example to set something like :
`$scope.countriesList = [{....}]` and have it immediate effect on the select options.
For example, there might be uses cases where in the app you might have several selects (ie Select your country of residence and Select your nationality) and want to restrict the countries list in one of them to some "available" countries.
OR having a first select with "Select your region : America/Europa/Asia" and then having a second select with only the countries from this region...

**Comment by Puigcerber** [comment]
Then I think you would better off using `ngOptions` with whatever list of countries you set in the controller.
